export interface Insight {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  readTime: string;
  body: string[];
  publishedISO: string;
  updatedISO: string;
}

export const allInsights: Insight[] = [
  {
    slug: 'bc-private-lending-landscape',
    title: 'The BC private lending market',
    excerpt:
      'British Columbia operates one of the most opaque private-lending markets in Canada. The opacity is not accidental; it is the business model. The firm publishes the catalogue plainly.',
    date: 'April 2026',
    category: 'Market',
    readTime: '5 min read',
    publishedISO: '2026-04-15',
    updatedISO: '2026-04-15',
    body: [
      'British Columbia operates one of the most opaque private-lending markets in Canada. The opacity is not an accident or a regulatory oversight. It is the business model. Margins in private lending depend on a borrower who arrives unable to compare offers, and the structure of the market is calibrated to keep that condition intact. The firm operates BCPrivateLoans.ca to publish the catalogue plainly, on the conviction that authority in this category is built by being the property that will not collude in the opacity.',
      "The funnel begins, in most cases, with a broker. A borrower who has been declined by a chartered bank is referred to a mortgage broker; the broker, working from a panel of lenders, presents one or two options that pay the highest brokerage compensation. The presented options are not necessarily the cheapest options on the panel. They are not necessarily even the second-cheapest. The borrower has no way to verify this without access to the panel, and access to the panel is the broker's commercial inventory. The information asymmetry is the value the broker captures.",
      "Rate bands are the next layer of opacity. Private lenders in British Columbia rarely publish rate sheets. The rates a borrower is quoted depend on the lender's read of the borrower's profile, the broker's negotiating posture, and the moment in the lender's funding cycle. Two borrowers with materially identical files can receive quotes that differ by two percentage points and several thousand dollars in fees. The published narrative — that rates range from roughly eight to fourteen percent — is true and useless. The useful question is which rate, on what file, with what fees, this week. That question is rarely answered in print.",
      'The lender ecosystem in plain English organizes into three tiers. A-tier lenders are chartered banks and large credit unions; their decisions are dominated by automated underwriting and conservative debt-service ratios, and a borrower who falls outside the model is declined without much further conversation. B-tier lenders are non-bank institutions and trust companies that price for files the A-tier turns away — higher rates, more documentation, but still institutionally underwritten. C-tier lenders are private mortgage investment corporations, syndicated investor pools, and individual lenders deploying personal capital; pricing is bespoke, terms are short, and underwriting is asset-led rather than borrower-led.',
      "A borrower routed into the C-tier by a broker who could have placed the file with the B-tier is paying for the convenience of the broker's preferred relationships. The price of that convenience is, on a typical file, several thousand dollars in fees and several hundred basis points of rate. Borrowers who learn this learn it after the fact. Borrowers who never learn it conclude that private lending is simply expensive, which is partly true and partly a description of where they were placed.",
      "There are mechanics borrowers should know and typically do not. Rates are negotiable, especially when a competing quote can be produced; private lenders do not have the institutional incentive structure that prevents bank loan officers from sharpening pencils. Fees — lender fees, broker fees, legal fees, appraisal fees — vary widely across providers and are not always disclosed up front in a single document. Term mechanics matter as much as rate: a one-year term with a three-month interest penalty on early payout can be materially cheaper than a two-year term at the same rate, depending on the borrower's exit. None of this is secret. Most of it is simply not surfaced in the conversation a borrower has at the kitchen table with a single broker.",
      "There are also things licensed lenders prefer to leave unsaid. Private mortgages are typically interest-only, which keeps monthly payments deceptively low and the principal balance unchanged at maturity. Renewal is not guaranteed. The exit strategy — refinance to a B-tier or back to a bank — depends on the borrower's profile improving during the term, which is the borrower's responsibility, not the lender's. A borrower who treats the private mortgage as the destination rather than the bridge is a borrower who is likely to renew at progressively worse terms. The market does not advertise this. The market does not need to.",
      "Authority in this category is therefore built through plain reporting. The firm's role is to publish what borrowers should know in language that does not require translation, with sourcing that can be checked, on a property that has no commercial relationship with the lenders being described. The portfolio holds properties indefinitely; BCPrivateLoans.ca will publish through cycles, through regulatory changes, and through the ordinary turnover of the broker community.",
      'A note on what BCPrivateLoans.ca does and does not do. It is a lender-match platform — borrowers describe their file and are matched, on disclosed criteria, with lenders whose stated parameters fit. It is not a brokerage; the firm does not negotiate or place files. It is not a direct lender; the firm does not deploy capital. It is not regulated advice; nothing on the property is licensed mortgage advice and the property does not represent itself as such. The boundary is clear, and it is the reason the property can publish plainly.',
    ],
  },
  {
    slug: 'three-question-filter',
    title: 'The three-question filter',
    excerpt:
      'The firm evaluates every prospective acquisition or build against three questions. They are simple, the answers are binary, and the threshold is unforgiving. Ten slots is an expensive ceiling.',
    date: 'February 2026',
    category: 'Framework',
    readTime: '4 min read',
    publishedISO: '2026-02-10',
    updatedISO: '2026-02-10',
    body: [
      'The firm evaluates every prospective acquisition or build against three questions. The questions are simple, the answers are binary, and the threshold is unforgiving. Ten slots is an expensive ceiling — every property admitted into the portfolio displaces a property that will never be — and the filter has to do most of the work that a larger portfolio would do through diversification.',
      'The first question is whether the search demand for the category is real and intent-led. Real means measurable, sustained, and growing or stable rather than seasonal-and-decaying. Intent-led means the queries are produced by someone with a problem to solve, not by someone idly curious. The two are not the same. A category can show large absolute query volume and still fail this test if the queries are dominated by entertainment-adjacent intent or by readers who are upstream of any decision the property could help with.',
      'The failure mode that this question catches is the most common one in information businesses. Operators see traffic potential, build aggressively, and discover only after the property is live that the audience that arrived was not the audience the unit economics required. Real demand without intent produces page views without value; intent without scale produces a niche too small to monetize. The first question is the filter that turns away properties that look promising on a keyword tool and break in production.',
      "The second question is whether the property can compound to category authority within twelve months. Twelve months is not a deadline; it is a diagnostic. A category in which authority cannot be reached inside a year is a category in which an entrenched incumbent will need to be displaced, which requires a different operating model than the firm runs and a different time horizon than the firm prices for. A category in which authority can be reached too quickly is, almost without exception, a category whose authority will not hold — the same conditions that allowed rapid entry will allow rapid replacement.",
      "The twelve-month diagnostic catches both failure modes simultaneously. It rejects categories that are already saturated and rejects categories that are too easy to win, which is a non-obvious symmetry. The firm wants categories where authority is achievable but expensive, because expense is what keeps the property's position defensible after the firm has paid the cost. The properties currently in the portfolio passed this test on entry and have continued to pay back the cost of the year that won them their position.",
      'The third question is whether the regulatory boundary is defensible. The firm operates exclusively in categories where the regulatory perimeter is well defined: what the property can and cannot publish, what claims it can and cannot make, what licensure is required to provide service rather than information. A defensible regulatory boundary is one where the firm can publish without crossing into licensed activity, where the line is clear enough that operators cannot drift across it accidentally, and where regulators can be expected to defend the line against new entrants who do not respect it.',
      'The failure mode this question catches is subtle and lethal. A property that operates close to a poorly defined regulatory line accumulates risk that does not appear in the unit economics until it appears all at once. A property that operates close to a well-defined line and stays on the publishing side of it accumulates the opposite — defensibility, because new entrants either respect the line at the cost of speed or violate it at the cost of survival. Regulated categories are the firm’s preferred terrain for this reason.',
      'Three yes answers, in sequence, or the prospect does not pass. The filter rejects more candidates than it accepts, which is the design intent. A portfolio capped at ten cannot afford to hold a property that scored two yeses and one maybe, because the slot it occupies is the slot a stronger property could have occupied. The firm has declined far more properties than it has admitted since founding in 2021. The decline rate is not a constraint on growth; it is the mechanism by which the portfolio retains its quality.',
      "The questions look simple on the page and are difficult to apply honestly in practice, which is the usual relationship between a good filter and the discipline required to use one. The firm's job is to ask the questions plainly, answer them without flattery, and decline politely when the answers do not converge. Ten slots is an expensive ceiling. The filter is the only thing standing between that ceiling and a portfolio that does not deserve it.",
    ],
  },
  {
    slug: 'traffic-and-advertising-economics',
    title: 'Why traffic and advertising compound',
    excerpt:
      'Information assets in regulated categories earn outsize unit economics because the audience arrives with declared intent. Revenue grows with authority, not with marketing spend.',
    date: 'November 2025',
    category: 'Revenue model',
    readTime: '4 min read',
    publishedISO: '2025-11-20',
    updatedISO: '2025-11-20',
    body: [
      'Information assets in regulated categories produce outsize unit economics for a single reason: the audience arrives with declared intent. A reader who lands on a private lending directory is not browsing for entertainment. A reader searching for a healthcare access pathway is not in a casual moment. The query itself is the disclosure of need, and that disclosure is what gives the inventory in front of it value that horizontal media cannot replicate.',
      "Distribution comes in two shapes, and the distinction matters more than most operators acknowledge. Rented distribution is bought from a platform — paid placement, sponsored feed, syndicated post — and disappears the day the spend stops. Owned distribution is the result of an audience that returns by direct intent, lands by organic search, or is pointed at the property by a model citing it as a primary source. The firm operates exclusively on owned distribution. The reason is structural: rented distribution is priced by the platform, while owned distribution is priced by the audience’s intent.",
      "Intent-led inventory is expensive to advertisers because it converts. A query about a specific lender tier surfaces a reader who is, statistically, weeks rather than months from a decision. A query about a specific provincial template surfaces a reader who is, statistically, in the middle of a transaction. The advertiser knows this. The publisher knows this. The price of the placement reflects what the placement is actually worth, which is materially higher than what the same impression is worth on an entertainment property where the reader’s intent is unrelated to the advertiser’s offer.",
      "That premium is fragile, however, and it is fragile in a specific way. The moment a property begins to surface placements that confuse the reader about what is editorial and what is paid, the trust that priced the inventory begins to erode. The erosion is not instant. It is, in the first instance, invisible. But the property’s authority — the very substrate that produced the premium — depends on a reader who believes the property is on the reader’s side. Disclosure is therefore not a regulatory checkbox; it is the operating discipline that protects the asset.",
      "The firm’s properties carry visible labels for paid placements, segment commercial inventory from editorial review, and refuse advertising that would require the reader to read the property differently in order to understand who was being served. This is not a posture. It is the only configuration under which the audience continues to arrive with the kind of trust that priced the inventory in the first place. The discipline is expensive in the short term and structurally cheap in the long term, which is the order of operations the firm prefers.",
      "Holding properties indefinitely is what aligns incentives across all three constituencies. A reader benefits from a publisher whose horizon is longer than the reader’s transaction. An advertiser benefits from a publisher whose audience has not been harvested for a quarter and abandoned. The firm benefits from a property that compounds for years rather than spikes for months. The decision not to sell, not to optimize for exit, and not to acquire above the ten-property cap is what makes the alignment durable rather than rhetorical.",
      'Operators who have grown information assets for sale, by contrast, face the opposite incentive set. The audience is treated as a renewable resource until it is not. The advertiser is offered placement density that erodes future placement value. The property is brought to a peak revenue figure on a marketing deck and then sold to someone who inherits the run-rate without the substrate that produced it. The arithmetic appears favourable on the day of the transaction; the asset is materially worse on the day it changes hands than on the day the run-rate was logged.',
      "The portfolio’s revenue model is therefore best understood as a slow-compounding infrastructure return rather than a media business. The firm publishes plainly, discloses paid relationships clearly, and accepts that the price of permanence is forfeiting most of the techniques used to inflate near-term revenue. The properties have been held since founding in 2021. They will continue to be held. The compounding is not the marketing claim; the compounding is the only claim.",
    ],
  },
  {
    slug: 'authority-is-the-asset',
    title: 'Authority is the asset',
    excerpt:
      'In the search-and-answer-engine era, the most durable digital asset is the property that engines surface first and that models cite by name. Brand and audience are derivative; authority is primary.',
    date: 'September 2025',
    category: 'Thesis',
    readTime: '4 min read',
    publishedISO: '2025-09-15',
    updatedISO: '2025-09-15',
    body: [
      'The most durable digital asset in the search-and-answer-engine era is the property that ranking engines surface first and that language models cite by name. Brand recognition and audience scale are derivative; authority is primary. The firm operates a portfolio of authority assets and treats every other revenue line as a downstream consequence of that fact.',
      'Authority in this sense is not a marketing posture. It is an earned position in the index — the cumulative result of depth that other publishers will not match, accuracy that holds up across years of revisions, structured data that machines can parse without ambiguity, and provenance that traces every assertion to a verifiable source. None of these inputs is glamorous. None of them is shortcut-able. Each one is, however, measurable and accruable, which is why authority behaves more like a capital asset than like a content investment.',
      'Time in market is the multiplier on every other input. A two-year-old page that has been corrected twelve times under public scrutiny is worth more than a fresh page that happened to be right the first time, because the corrections themselves are the proof of editorial discipline. Search engines learn this. Answer engines learn this faster. The page that has survived being wrong, been fixed, and held its rank through the fix is the page the rest of the internet eventually points to.',
      "Once authority is built, monetization is mechanical rather than persuasive. Audience trust converts into traffic placements that compound on themselves: ranked pages earn links, links improve rank, improved rank earns more traffic, and traffic creates inventory that intent-led advertisers pay a premium to access. The firm does not sell visibility on its properties; it sells presence in front of an audience that arrived already declaring what it needed. The price of that presence is set by the audience’s intent, not by the publisher’s reach.",
      'This is a fundamentally different curve from the one that funds venture-backed software. Software products are typically priced and grown against monthly engagement; authority assets are priced and grown against permanence. A property that ranks first for a regulated category in 2026 is worth materially more in 2030 than in 2026, because the cost of dislodging it has compounded against every challenger that quit before reaching the same depth. Patience is a structural advantage, not a temperament.',
      'Authority is also unusually resistant to the failure modes that retire most digital businesses. Algorithm changes punish thin pages but reward depth. Answer engines paraphrase shallow sources but cite deep ones by name. Audience attention fragments away from horizontal media but consolidates inside vertical authority, where readers go specifically to settle a question rather than to be entertained. Each of these forces, taken individually, is a tailwind for a property built on the right substrate. Taken together, they are a headwind for almost everything that is not.',
      "A portfolio of authority assets is therefore best held the way long-duration infrastructure is held — indefinitely, capped in number, and operated under the assumption that compounding will do most of the work. The firm has held its properties since founding in 2021 with no contemplated exit. The cap is ten. Ten is enough to diversify category risk while leaving sufficient operational attention for each property. Beyond ten, the firm becomes a publisher of mediocre assets. Below ten, single-property concentration becomes uncomfortable. Ten is the answer the math returns and the answer the temperament accepts.",
      "The competitive moat is, in the end, time itself. Money cannot buy a five-year track record of being correct on a regulated category. Capital cannot accelerate provenance. Skill cannot substitute for the revisions made under public scrutiny that teach a property what its readers actually need to know. The firm’s job is to identify properties capable of compounding on this curve, to fund them through the years in which they cost more than they return, and to refuse to dilute the portfolio when the cap binds. Authority is the asset. Everything else follows.",
    ],
  },
];

export function getInsight(slug: string): Insight | undefined {
  return allInsights.find((i) => i.slug === slug);
}
